name: Automate changeset feedback
on:
  - pull_request_target

permissions:
  pull-requests: write
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pages: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  feedback:
    # prevent running towards forks and version packages
    if: github.repository == 'djamaile/backstage'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.email noreply@backstage.io
          git config --global user.name 'Github changeset workflow'
          git status
      - uses: backstage/actions/changeset-feedback@v0.5.9
        with:
          # Fetch the commit that's merged into the base rather than the target ref
          # This will let us diff only the contents of the PR, without fetching more history
          diffRef: 'refs/pull/${{ github.event.pull_request.number }}/merge'
          github-token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN  }}
          issue-number: ${{ steps.pr-number.outputs.pr-number }}
          app-id: ${{ secrets.BACKSTAGE_GOALIE_APPLICATION_ID }}