name: Automate changeset feedback
on:
  - pull_request_target

permissions:
  pull-requests: write
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pages: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  feedback:
    # prevent running towards forks and version packages
    if: github.repository == 'djamaile/backstage'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        run: git fetch origin main
      - uses: backstage/actions/changeset-feedback@changeset-patches
        name: Generate feedback
        with:
          # Fetch the commit that's merged into the base rather than the target ref
          # This will let us diff only the contents of the PR, without fetching more history
          diffRef: 'origin/main'
          github-token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN  }}
          issue-number: ${{ steps.pr-number.outputs.pr-number }}
          app-id: ${{ secrets.APP_ID }}
          private-key:  ${{ secrets.PRIVATE_KEY  }}
          installation-id: ${{ secrets.INSTALLATION_ID }}