name: CI
on:
  pull_request:
    paths-ignore:
      - 'microsite/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # This step only runs yarn install to make sure that an exact match is available
  # in the cache. The two following verify and tests jobs then always install from cache.
  install:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: backstage/actions/changeset-feedback@changeset-patches
        with:
          # Fetch the commit that's merged into the base rather than the target ref
          # This will let us diff only the contents of the PR, without fetching more history
          diffRef: 'refs/pull/${{ github.event.pull_request.number }}/merge'
          github-token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN  }}
          issue-number: github.event.pull_request.number
