name: CI
on:
  pull_request:
    paths-ignore:
      - 'microsite/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # This step only runs yarn install to make sure that an exact match is available
  # in the cache. The two following verify and tests jobs then always install from cache.
  install:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - name: Checkouts
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.email noreply@backstage.io
          git config --global user.name 'Github changeset workflow'
          git diff origin/master
      - uses: backstage/actions/changeset-feedback@changeset-patches
        name: Generate changeset
        with:
          # Fetch the commit that's merged into the base rather than the target ref
          # This will let us diff only the contents of the PR, without fetching more history
          diffRef: 'origin/master'
          github-token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN  }}
          issue-number: github.event.pull_request.number
          app-id: djamaile
          private-key: djamaile
          installation-id: djamaile
